# Generated by Django 3.1 on 2022-11-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppty', '0003_buy_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('property_description', models.CharField(max_length=100)),
            ],
        ),
    ]
