# Generated by Django 3.1 on 2022-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppty', '0005_mortgage_property_rent_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_property',
            name='property_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='mortgage_property',
            name='property_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='rent_property',
            name='property_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='sale_property',
            name='property_price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
