# Generated by Django 3.1 on 2022-11-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppty', '0007_auto_20221105_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_property',
            name='property_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mortgage_property',
            name='property_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rent_property',
            name='property_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale_property',
            name='property_price',
            field=models.FloatField(default=0),
        ),
    ]
